name: nostr_console
description: A multi-platform nostr client built for terminal/console
version: 0.2.9-beta
homepage: https://github.com/vishalxl/nostr_console 


#0.2.9
# improved fetching logic
# added more relays 



#0.2.8 
# reduced items fetched. 23/12
# reduced items more  evening 23/12
# reduced more evening 23/12
# channel fetches for 3-4 days


#0.2.7
# improved relay, fetching logic and added more default pubkeys to fetch
# incresed user id lenth to 5, and event id len to 6 in SN
 
# after tagging
# fixed new issue of taking longer time when file was already there
# increased channel fetches from 2 days from half a day 


environment:
  sdk: '>=2.17.3 <3.0.0'


dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.4
dependencies:
  args: ^2.3.1
  bip340: ^0.0.4
  cli_menu: ^0.3.0-nullsafety.0
  crypto: ^3.0.2
  intl: ^0.17.0
  translator: ^0.1.7
  web_socket_channel: ^2.2.0
  logging: ^1.0.2
  kepler: ^1.0.3
  qr: ^3.0.1
