name: nostr_console
description: A multi-platform nostr client built for terminal/console.
version: 0.0.7-beta
homepage: https://github.com/vishalxl/nostr_console 


# building with thread end marks

environment:
  sdk: '>=2.17.3 <3.0.0'


dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.4
dependencies:
  args: ^2.3.1
  bip340: ^0.0.4
  cli_menu: ^0.3.0-nullsafety.0
  crypto: ^3.0.2
  intl: ^0.17.0
  translator: ^0.1.7
  web_socket_channel: ^2.2.0
  logging: ^1.0.2
  kepler: ^1.0.3
#  secp256k1cipher: ^0.2.7
